// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: MplSalesConfirm.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct IGPMplSalesConfirm: SwiftProtobuf.RequestMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpRequest: IGPRequest {
    get {return _storage._igpRequest ?? IGPRequest()}
    set {_uniqueStorage()._igpRequest = newValue}
  }
  /// Returns true if `igpRequest` has been explicitly set.
  public var hasIgpRequest: Bool {return _storage._igpRequest != nil}
  /// Clears the value of `igpRequest`. Subsequent reads from it will return its default value.
  public mutating func clearIgpRequest() {_uniqueStorage()._igpRequest = nil}

  public var igpInvoiceNumber: Int64 {
    get {return _storage._igpInvoiceNumber}
    set {_uniqueStorage()._igpInvoiceNumber = newValue}
  }

  public var igpConfirm: IGPMplSalesConfirm.IGPConfirm {
    get {return _storage._igpConfirm}
    set {_uniqueStorage()._igpConfirm = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum IGPConfirm: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case confirm // = 0
    case reverse // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .confirm
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .confirm
      case 1: self = .reverse
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .confirm: return 0
      case .reverse: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension IGPMplSalesConfirm.IGPConfirm: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [IGPMplSalesConfirm.IGPConfirm] = [
    .confirm,
    .reverse,
  ]
}

#endif  // swift(>=4.2)

public struct IGPMplSalesConfirmResponse: SwiftProtobuf.ResponseMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpResponse: IGPResponse {
    get {return _storage._igpResponse ?? IGPResponse()}
    set {_uniqueStorage()._igpResponse = newValue}
  }
  /// Returns true if `igpResponse` has been explicitly set.
  public var hasIgpResponse: Bool {return _storage._igpResponse != nil}
  /// Clears the value of `igpResponse`. Subsequent reads from it will return its default value.
  public mutating func clearIgpResponse() {_uniqueStorage()._igpResponse = nil}

  public var igpInvoiceNumber: Int64 {
    get {return _storage._igpInvoiceNumber}
    set {_uniqueStorage()._igpInvoiceNumber = newValue}
  }

  public var igpFromUserID: Int64 {
    get {return _storage._igpFromUserID}
    set {_uniqueStorage()._igpFromUserID = newValue}
  }

  public var igpAmount: Int64 {
    get {return _storage._igpAmount}
    set {_uniqueStorage()._igpAmount = newValue}
  }

  public var igpTraceNumber: Int64 {
    get {return _storage._igpTraceNumber}
    set {_uniqueStorage()._igpTraceNumber = newValue}
  }

  public var igpPayTime: Int32 {
    get {return _storage._igpPayTime}
    set {_uniqueStorage()._igpPayTime = newValue}
  }

  public var igpDescription: String {
    get {return _storage._igpDescription}
    set {_uniqueStorage()._igpDescription = newValue}
  }

  public var igpCardNumber: String {
    get {return _storage._igpCardNumber}
    set {_uniqueStorage()._igpCardNumber = newValue}
  }

  public var igpRrn: Int64 {
    get {return _storage._igpRrn}
    set {_uniqueStorage()._igpRrn = newValue}
  }

  public var igpStatus: IGPMplSalesConfirmResponse.IGPStatus {
    get {return _storage._igpStatus}
    set {_uniqueStorage()._igpStatus = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum IGPStatus: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case pendingVerify // = 0
    case success // = 1
    case failed // = 2
    case reversed // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .pendingVerify
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .pendingVerify
      case 1: self = .success
      case 2: self = .failed
      case 3: self = .reversed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .pendingVerify: return 0
      case .success: return 1
      case .failed: return 2
      case .reversed: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension IGPMplSalesConfirmResponse.IGPStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [IGPMplSalesConfirmResponse.IGPStatus] = [
    .pendingVerify,
    .success,
    .failed,
    .reversed,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension IGPMplSalesConfirm: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPMplSalesConfirm"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_request"),
    2: .standard(proto: "IGP_invoice_number"),
    3: .standard(proto: "IGP_confirm"),
  ]

  fileprivate class _StorageClass {
    var _igpRequest: IGPRequest? = nil
    var _igpInvoiceNumber: Int64 = 0
    var _igpConfirm: IGPMplSalesConfirm.IGPConfirm = .confirm

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpRequest = source._igpRequest
      _igpInvoiceNumber = source._igpInvoiceNumber
      _igpConfirm = source._igpConfirm
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpRequest)
        case 2: try decoder.decodeSingularInt64Field(value: &_storage._igpInvoiceNumber)
        case 3: try decoder.decodeSingularEnumField(value: &_storage._igpConfirm)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpRequest {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpInvoiceNumber != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpInvoiceNumber, fieldNumber: 2)
      }
      if _storage._igpConfirm != .confirm {
        try visitor.visitSingularEnumField(value: _storage._igpConfirm, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPMplSalesConfirm, rhs: IGPMplSalesConfirm) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpRequest != rhs_storage._igpRequest {return false}
        if _storage._igpInvoiceNumber != rhs_storage._igpInvoiceNumber {return false}
        if _storage._igpConfirm != rhs_storage._igpConfirm {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IGPMplSalesConfirm.IGPConfirm: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CONFIRM"),
    1: .same(proto: "REVERSE"),
  ]
}

extension IGPMplSalesConfirmResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPMplSalesConfirmResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_response"),
    2: .standard(proto: "IGP_invoice_number"),
    3: .standard(proto: "IGP_from_user_id"),
    4: .standard(proto: "IGP_amount"),
    5: .standard(proto: "IGP_trace_number"),
    6: .standard(proto: "IGP_pay_time"),
    7: .standard(proto: "IGP_description"),
    8: .standard(proto: "IGP_card_number"),
    9: .standard(proto: "IGP_rrn"),
    10: .standard(proto: "IGP_status"),
  ]

  fileprivate class _StorageClass {
    var _igpResponse: IGPResponse? = nil
    var _igpInvoiceNumber: Int64 = 0
    var _igpFromUserID: Int64 = 0
    var _igpAmount: Int64 = 0
    var _igpTraceNumber: Int64 = 0
    var _igpPayTime: Int32 = 0
    var _igpDescription: String = String()
    var _igpCardNumber: String = String()
    var _igpRrn: Int64 = 0
    var _igpStatus: IGPMplSalesConfirmResponse.IGPStatus = .pendingVerify

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpResponse = source._igpResponse
      _igpInvoiceNumber = source._igpInvoiceNumber
      _igpFromUserID = source._igpFromUserID
      _igpAmount = source._igpAmount
      _igpTraceNumber = source._igpTraceNumber
      _igpPayTime = source._igpPayTime
      _igpDescription = source._igpDescription
      _igpCardNumber = source._igpCardNumber
      _igpRrn = source._igpRrn
      _igpStatus = source._igpStatus
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpResponse)
        case 2: try decoder.decodeSingularInt64Field(value: &_storage._igpInvoiceNumber)
        case 3: try decoder.decodeSingularInt64Field(value: &_storage._igpFromUserID)
        case 4: try decoder.decodeSingularInt64Field(value: &_storage._igpAmount)
        case 5: try decoder.decodeSingularInt64Field(value: &_storage._igpTraceNumber)
        case 6: try decoder.decodeSingularInt32Field(value: &_storage._igpPayTime)
        case 7: try decoder.decodeSingularStringField(value: &_storage._igpDescription)
        case 8: try decoder.decodeSingularStringField(value: &_storage._igpCardNumber)
        case 9: try decoder.decodeSingularInt64Field(value: &_storage._igpRrn)
        case 10: try decoder.decodeSingularEnumField(value: &_storage._igpStatus)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpResponse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpInvoiceNumber != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpInvoiceNumber, fieldNumber: 2)
      }
      if _storage._igpFromUserID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpFromUserID, fieldNumber: 3)
      }
      if _storage._igpAmount != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpAmount, fieldNumber: 4)
      }
      if _storage._igpTraceNumber != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpTraceNumber, fieldNumber: 5)
      }
      if _storage._igpPayTime != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpPayTime, fieldNumber: 6)
      }
      if !_storage._igpDescription.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpDescription, fieldNumber: 7)
      }
      if !_storage._igpCardNumber.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpCardNumber, fieldNumber: 8)
      }
      if _storage._igpRrn != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpRrn, fieldNumber: 9)
      }
      if _storage._igpStatus != .pendingVerify {
        try visitor.visitSingularEnumField(value: _storage._igpStatus, fieldNumber: 10)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPMplSalesConfirmResponse, rhs: IGPMplSalesConfirmResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpResponse != rhs_storage._igpResponse {return false}
        if _storage._igpInvoiceNumber != rhs_storage._igpInvoiceNumber {return false}
        if _storage._igpFromUserID != rhs_storage._igpFromUserID {return false}
        if _storage._igpAmount != rhs_storage._igpAmount {return false}
        if _storage._igpTraceNumber != rhs_storage._igpTraceNumber {return false}
        if _storage._igpPayTime != rhs_storage._igpPayTime {return false}
        if _storage._igpDescription != rhs_storage._igpDescription {return false}
        if _storage._igpCardNumber != rhs_storage._igpCardNumber {return false}
        if _storage._igpRrn != rhs_storage._igpRrn {return false}
        if _storage._igpStatus != rhs_storage._igpStatus {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IGPMplSalesConfirmResponse.IGPStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PENDING_VERIFY"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "FAILED"),
    3: .same(proto: "REVERSED"),
  ]
}
